import fs from 'node:fs/promises';
import path from 'node:path';
import { pathToFileURL } from 'node:url';
import { Presentation, PresentationFile } from '@oai/artifact-tool';

const workspaceDir = '/home/sahil/Projects/ArtifactAlley';
const SKILL_DIR = '/home/sahil/.codex/plugins/cache/openai-primary-runtime/presentations/26.905.11957/skills/presentations';
const TMP_DIR = path.join(workspaceDir, '.artifact-ppt-build');
const FINAL_PPTX = path.join(workspaceDir, 'presentation-output', 'Artifact_Alley_College_Project_Presentation_v3.pptx');
const RUNTIME_PYTHON = '/home/sahil/.cache/codex-runtimes/codex-primary-runtime/dependencies/python/bin/python3';
const { resolvePresentationFont, finalizePresentation } = await import(pathToFileURL(path.join(SKILL_DIR, 'container_tools/artifact_tool_utils.mjs')).href);
const family = resolvePresentationFont();
const deck = Presentation.create({ slideSize: { width: 1280, height: 720 } });

const C = { navy: '#10263F', blue: '#1B5E7A', teal: '#2D8C91', gold: '#D99A31', cream: '#F7F3EC', ink: '#17212B', muted: '#54616D', line: '#D7DFE4', white: '#FFFFFF', pale: '#EAF3F4' };
const P = (slide, left, top, width, height, fill = 'none', radius = 0) => slide.shapes.add({ geometry: radius ? 'roundRect' : 'rect', position: { left, top, width, height }, fill, line: { fill: 'none', width: 0 }, borderRadius: radius });
const T = (slide, text, left, top, width, height, size = 22, color = C.ink, bold = false, align = 'left') => {
  const s = slide.shapes.add({ geometry: 'textbox', position: { left, top, width, height }, fill: 'none', line: { fill: 'none', width: 0 } });
  s.text = text; s.text.style = { typeface: family, fontSize: size, color, bold, alignment: align, autoFit: 'shrinkText' }; return s;
};
const title = (slide, n, text, sub = '') => { slide.background.fill = C.cream; P(slide, 0, 0, 1280, 16, C.gold); T(slide, text, 70, 90, 1040, 60, 32, C.navy, true); if (sub) T(slide, sub, 72, 148, 1020, 28, 16, C.muted); T(slide, `Artifact Alley  |  ${String(n).padStart(2, '0')}`, 1070, 666, 150, 22, 12, C.muted, false, 'right'); };
const dot = (slide, x, y, num, heading, body, accent = C.teal) => { P(slide, x, y, 54, 54, accent, 27); T(slide, String(num), x, y + 10, 54, 28, 18, C.white, true, 'center'); T(slide, heading, x + 72, y + 3, 250, 28, 21, C.navy, true); T(slide, body, x + 72, y + 36, 285, 55, 15.5, C.muted); };
const note = (slide, text) => { slide.speakerNotes.textFrame.setText(text); };
const repoImage = async (name) => new Uint8Array(await fs.readFile(path.join(workspaceDir, 'src/main/resources/static/images', name)));
const seller = await repoImage('seller.png'); const bidding = await repoImage('bidding.png');

// 1 Cover
{ const s = deck.slides.add(); s.background.fill = C.navy; P(s, 0, 0, 1280, 720, C.navy); P(s, 0, 0, 1280, 12, C.gold); P(s, 805, 96, 360, 360, C.teal, 180); s.images.add({ blob: bidding, contentType: 'image/png', alt: 'Auction bidding illustration', fit: 'contain', position: { left: 830, top: 122, width: 310, height: 310 } }); T(s, 'Artifact Alley', 82, 152, 650, 70, 52, C.white, true); T(s, 'Online Auction Platform for Artifacts and Antiques', 84, 232, 590, 62, 26, '#CBE3E4'); T(s, 'College Project Presentation', 84, 326, 370, 30, 19, C.gold, true); T(s, 'Proposed completed-system overview', 84, 378, 445, 28, 18, C.white); T(s, 'A role-based platform for trusted artifact discovery, approval, and bidding', 84, 468, 555, 58, 20, '#DDE8EE'); note(s, 'This deck presents the intended completed version of Artifact Alley. It does not claim that every planned feature is already implemented.'); }

// 2 Context
{ const s = deck.slides.add(); title(s, 2, 'Why Artifact Alley', 'The project addresses the difficulty of organizing trusted online auctions for artifacts and antiques.'); P(s, 72, 174, 498, 392, C.white, 20); T(s, 'Current difficulty', 112, 214, 330, 34, 24, C.navy, true); T(s, 'Collectors need a clear way to discover items, follow active auctions, and place bids. Sellers need a controlled path to publish listings. An administrator needs oversight before an item appears publicly.', 112, 276, 395, 184, 21, C.ink); P(s, 642, 174, 565, 392, C.pale, 20); T(s, 'Project response', 686, 214, 360, 34, 24, C.navy, true); dot(s, 686, 286, 1, 'Discover', 'Browse a curated catalogue of live auction items.', C.teal); dot(s, 686, 390, 2, 'Participate', 'Sign in and place a valid bid on an active item.', C.gold); dot(s, 686, 494, 3, 'Supervise', 'Review seller submissions before public release.', C.blue); note(s, 'Class presentation convention used: state the problem first, then explain the solution in plain terms.'); }

// 3 Objectives
{ const s = deck.slides.add(); title(s, 3, 'Project objectives', 'The completed system will support the main auction journey while keeping actions tied to user roles.'); const items = [ ['Trusted access', 'Create accounts and sign in with server-side validation and secure password storage.'], ['Controlled listing', 'Let sellers submit artifact listings for review before publication.'], ['Fair bidding', 'Accept bids only when the auction is live and the amount meets the required minimum.'], ['Administrative review', 'Allow an administrator to approve suitable submissions and manage the marketplace.'] ]; items.forEach((it, i) => { const x = 72 + (i % 2) * 570, y = 174 + Math.floor(i / 2) * 205; P(s, x, y, 530, 160, C.white, 18); P(s, x + 28, y + 31, 14, 96, i % 2 ? C.gold : C.teal, 7); T(s, it[0], x + 66, y + 31, 420, 30, 23, C.navy, true); T(s, it[1], x + 66, y + 76, 410, 58, 17, C.muted); }); }

// 4 Users
{ const s = deck.slides.add(); title(s, 4, 'Users and responsibilities', 'Role-based access keeps each part of the marketplace focused and accountable.'); const roles = [ ['Bidder', 'Browse live auctions\nView auction details\nPlace valid bids'], ['Seller', 'Register as a seller\nSubmit an artifact\nTrack approval status'], ['Administrator', 'Review pending listings\nApprove listings\nMaintain marketplace quality'] ]; roles.forEach((r, i) => { const x = 86 + i * 390; P(s, x, 184, 330, 320, i === 2 ? C.navy : C.white, 20); P(s, x, 184, 330, 10, i === 1 ? C.gold : C.teal, 0); T(s, r[0], x + 34, 232, 260, 38, 27, i === 2 ? C.white : C.navy, true); T(s, r[1], x + 34, 302, 250, 145, 19, i === 2 ? '#DCEBF0' : C.muted); }); T(s, 'A visitor may browse the catalogue. Account-only actions require the relevant role.', 160, 565, 960, 30, 19, C.blue, false, 'center'); }

// 5 Workflow
{ const s = deck.slides.add(); title(s, 5, 'How the completed system will work', 'The public auction flow begins with a seller submission and ends with a bidder action on a live listing.'); const labels = [ ['Seller submits\nartifact', 80], ['Admin reviews\nsubmission', 340], ['Approved listing\nbecomes live', 600], ['Bidder views\nand bids', 860] ]; const shapes = labels.map(([tx, x], i) => { const sh = P(s, x, 290, 205, 125, i === 2 ? C.teal : C.white, 18); T(s, tx, x + 20, 325, 165, 58, 20, i === 2 ? C.white : C.navy, true, 'center'); return sh; }); for (let i = 0; i < 3; i++) s.shapes.connect(shapes[i], shapes[i + 1], { kind: 'straight', fromSide: 'right', toSide: 'left', line: { style: 'solid', fill: C.gold, width: 3 }, tail: { type: 'arrow', width: 'med', length: 'med' } }); T(s, 'Approval protects the public catalogue. Bid rules protect the auction process.', 180, 514, 920, 34, 20, C.muted, false, 'center'); }

// 6 Architecture
{ const s = deck.slides.add(); title(s, 6, 'Proposed system architecture', 'A layered Spring application separates the browser experience, business rules, and stored data.'); const browser = P(s, 88, 275, 220, 120, C.white, 18); const web = P(s, 405, 245, 250, 180, C.pale, 18); const data = P(s, 758, 275, 220, 120, C.white, 18); const deploy = P(s, 1064, 275, 135, 120, C.navy, 18); T(s, 'Browser', 122, 300, 155, 32, 24, C.navy, true, 'center'); T(s, 'JSP pages\nCSS', 122, 341, 155, 45, 18, C.muted, false, 'center'); T(s, 'Spring Boot', 440, 270, 180, 32, 25, C.navy, true, 'center'); T(s, 'Spring MVC controllers\nServices and validation\nSpring Data JPA', 440, 318, 180, 72, 18, C.ink, false, 'center'); T(s, 'Database', 794, 300, 150, 32, 24, C.navy, true, 'center'); T(s, 'H2 for local work\nPostgreSQL for deployment', 787, 341, 165, 45, 16, C.muted, false, 'center'); T(s, 'Deploy', 1080, 303, 100, 28, 22, C.white, true, 'center'); T(s, 'Render', 1080, 345, 100, 24, 17, '#DCEBF0', false, 'center'); [[browser,web],[web,data],[data,deploy]].forEach(([a,b]) => s.shapes.connect(a,b,{kind:'straight',fromSide:'right',toSide:'left',line:{style:'solid',fill:C.gold,width:3},tail:{type:'arrow',width:'med',length:'med'}})); note(s, 'Technology choices are based on the repository pom.xml and deployment documentation.'); }

// 7 Tech
{ const s = deck.slides.add(); title(s, 7, 'Technology stack', 'The stack matches the Java syllabus and supports a server-rendered web application.'); const tech = [ ['Language', 'Java 21'], ['Framework', 'Spring Boot 3.5'], ['Web layer', 'Spring MVC and JSP'], ['Data access', 'Spring Data JPA and JDBC'], ['Database', 'H2 locally; PostgreSQL in production'], ['Build and packaging', 'Maven and executable WAR'], ['Deployment', 'Docker on Render'] ]; tech.forEach((a, i) => { const col = i < 4 ? 0 : 1, row = i < 4 ? i : i - 4; const x = col ? 660 : 95, y = 170 + row * 105; P(s, x, y, 510, 78, C.white, 14); T(s, a[0], x + 28, y + 23, 175, 28, 18, C.muted, true); T(s, a[1], x + 210, y + 21, 265, 30, 20, C.navy, true); }); }

// 8 Feature view
{ const s = deck.slides.add(); title(s, 8, 'Expected completed experience', 'The target system creates a simple, auditable journey for each marketplace participant.'); s.images.add({ blob: seller, contentType: 'image/png', alt: 'Seller illustration', fit: 'contain', position: { left: 85, top: 185, width: 275, height: 275 } }); s.images.add({ blob: bidding, contentType: 'image/png', alt: 'Bidding illustration', fit: 'contain', position: { left: 885, top: 185, width: 275, height: 275 } }); T(s, 'Seller journey', 84, 502, 280, 30, 24, C.navy, true, 'center'); T(s, 'Create account, submit artifact, await approval', 82, 540, 285, 48, 17, C.muted, false, 'center'); T(s, 'Bidder journey', 886, 502, 270, 30, 24, C.navy, true, 'center'); T(s, 'Browse live items, inspect details, place a valid bid', 882, 540, 285, 48, 17, C.muted, false, 'center'); P(s, 397, 258, 488, 165, C.navy, 22); T(s, 'Marketplace quality', 435, 294, 410, 32, 27, C.white, true, 'center'); T(s, 'Only approved items appear in the live catalogue.\nBidding rules reject invalid actions.', 430, 342, 420, 52, 18, '#DCEBF0', false, 'center'); }

// 9 Expected impact and future scope
{ const s = deck.slides.add(); title(s, 9, 'Expected outcome and future scope', 'The project’s intended result is a structured auction workflow that can grow beyond the first release.'); P(s, 80, 176, 500, 360, C.white, 20); T(s, 'Expected outcome', 118, 215, 350, 32, 25, C.navy, true); T(s, 'A single web platform where:\n\n• bidders participate in live auctions\n• sellers submit artifacts through review\n• administrators control marketplace entry', 118, 278, 395, 165, 19, C.ink); P(s, 640, 176, 560, 360, C.pale, 20); T(s, 'Next planned capabilities', 684, 215, 390, 32, 25, C.navy, true); T(s, '• Artifact photos and richer catalogue information\n\n• Seller dashboard for submitted listings\n\n• Auction closing logic, winner notification, and payment integration', 684, 278, 440, 165, 19, C.ink); T(s, 'Future scope items are proposed, not presented as completed features.', 246, 586, 790, 26, 17, C.blue, false, 'center'); }

// 10 closing
{ const s = deck.slides.add(); s.background.fill = C.navy; P(s, 0, 0, 1280, 720, C.navy); P(s, 0, 0, 1280, 12, C.gold); T(s, 'Artifact Alley', 96, 165, 800, 62, 48, C.white, true); T(s, 'A proposed online auction platform for artifacts and antiques', 98, 245, 770, 34, 24, '#CBE3E4'); P(s, 98, 354, 520, 4, C.gold); T(s, 'The finished project will combine secure role-based access, controlled artifact approval, and valid bidding rules in one Spring-powered web application.', 98, 400, 700, 85, 23, C.white); T(s, 'Thank you', 98, 561, 230, 38, 29, C.gold, true); note(s, 'Research-informed flow used for this presentation: problem, solution, objectives, architecture, technology, expected result, and future scope. Sources consulted: University of Washington CSE 403 demo guidance and final-year software project presentation examples.'); }

await fs.mkdir(path.join(workspaceDir, '.codex-finalizer'), { recursive: true });
const candidatePath = path.join(TMP_DIR, 'candidate.pptx');
await (await PresentationFile.exportPptx(deck)).save(candidatePath);
const requirements = { explicitTotalSlideCount: 10, requiredNativeTableOwnerSlides: [], requiredNativeChartOwnerSlides: [] };
await finalizePresentation({ ...requirements, workspaceDir, candidatePath, finalPath: FINAL_PPTX, pythonExecutable: RUNTIME_PYTHON, integrityValidatorPath: path.join(SKILL_DIR, 'container_tools/inspect_presentation_package_integrity.py'), layoutValidatorPath: path.join(SKILL_DIR, 'container_tools/inspect_presentation_layout_geometry.py'), layoutArgs: ['--expected-slide-size-emu', '12192000,6858000', '--validate-bullet-geometry', '--validate-heading-fit'], fontPolicy: { basis: 'design', families: [family] }, verifyArtifactToolImport: true, receiptPath: path.join(workspaceDir, '.codex-finalizer', 'Artifact_Alley_College_Project_Presentation_v3.validation.json') });
