spring.datasource.url=${JDBC_DATABASE_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.h2.console.enabled=false
artifactalley.initial-admin-password=${INITIAL_ADMIN_PASSWORD}
