spring.application.name=artifact-alley
spring.profiles.default=local
server.port=${PORT:8080}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp
artifactalley.auction.minimum-increment=${AUCTION_MINIMUM_INCREMENT:100.00}
