spring.datasource.url=jdbc:h2:file:./data/artifactalley;AUTO_SERVER=TRUE
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
artifactalley.initial-admin-password=123456
