<%@ page contentType="text/html;charset=UTF-8" %>
<%@ taglib prefix="c" uri="jakarta.tags.core" %>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>My bids | Artifact Alley</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="/css/site.css" rel="stylesheet">
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark auction-nav"><div class="container"><a class="navbar-brand" href="/">Artifact Alley</a><div class="d-flex align-items-center gap-3"><span class="navbar-text"><c:out value="${sessionScope.signedInUser.name}" /> <small>(BIDDER)</small></span><a class="btn btn-outline-light btn-sm" href="/account/password">Change password</a><form action="/logout" method="post" class="m-0" id="logout-form"><input type="hidden" name="_csrf" value="${csrfToken}"><button class="btn btn-outline-light btn-sm" type="button" id="logout-trigger">Log out</button></form></div></div></nav>
<div class="logout-modal" id="logout-modal" hidden><section class="logout-dialog" role="dialog" aria-modal="true" aria-labelledby="logout-title" aria-describedby="logout-message"><h2 id="logout-title">Log out?</h2><p id="logout-message">Are you sure you want to log out of Artifact Alley?</p><div class="logout-actions"><button class="btn btn-outline-secondary" type="button" id="logout-cancel">Cancel</button><button class="btn btn-primary" type="button" id="logout-confirm">Log out</button></div></section></div>
<main class="container py-5">
    <p class="eyebrow text-dark">BIDDER ACTIVITY</p><h1>My bids</h1><p class="description mb-5">Follow auctions you have bid on and review their final outcomes.</p>
    <section class="activity-section mb-5" aria-labelledby="active-bids-title"><h2 id="active-bids-title">Active auctions</h2><c:choose><c:when test="${empty activity.active}"><p class="description empty-state">You have no active auctions.</p></c:when><c:otherwise><div class="row g-3"><c:forEach items="${activity.active}" var="entry"><div class="col-md-6 col-lg-4"><article class="activity-card h-100 p-4"><h3><a href="/artifacts/${entry.artifactId}"><c:out value="${entry.title}" /></a></h3><dl><div><dt>Your highest bid</dt><dd>₹ <c:out value="${entry.bidderBid}" /></dd></div><div><dt>Current price</dt><dd>₹ <c:out value="${entry.auctionPrice}" /></dd></div><div><dt>Closes</dt><dd><c:out value="${entry.closesAtDisplay}" /></dd></div><div><dt>Status</dt><dd><c:out value="${entry.status}" /> — <c:out value="${entry.outcome}" /></dd></div></dl></article></div></c:forEach></div></c:otherwise></c:choose></section>
    <section class="activity-section mb-5" aria-labelledby="won-bids-title"><h2 id="won-bids-title">Won auctions</h2><c:choose><c:when test="${empty activity.won}"><p class="description empty-state">You have not won an auction yet.</p></c:when><c:otherwise><div class="row g-3"><c:forEach items="${activity.won}" var="entry"><div class="col-md-6 col-lg-4"><article class="activity-card activity-card-won h-100 p-4"><span class="badge text-bg-success mb-3">Won</span><h3><a href="/artifacts/${entry.artifactId}"><c:out value="${entry.title}" /></a></h3><dl><div><dt>Your winning bid</dt><dd>₹ <c:out value="${entry.bidderBid}" /></dd></div><div><dt>Final price</dt><dd>₹ <c:out value="${entry.auctionPrice}" /></dd></div><div><dt>Closed</dt><dd><c:out value="${entry.closesAtDisplay}" /></dd></div><div><dt>Status</dt><dd><c:out value="${entry.status}" /></dd></div></dl></article></div></c:forEach></div></c:otherwise></c:choose></section>
    <section class="activity-section" aria-labelledby="ended-bids-title"><h2 id="ended-bids-title">Lost or ended auctions</h2><c:choose><c:when test="${empty activity.ended}"><p class="description empty-state">You have no lost or ended auctions.</p></c:when><c:otherwise><div class="row g-3"><c:forEach items="${activity.ended}" var="entry"><div class="col-md-6 col-lg-4"><article class="activity-card h-100 p-4"><h3><a href="/artifacts/${entry.artifactId}"><c:out value="${entry.title}" /></a></h3><dl><div><dt>Your highest bid</dt><dd>₹ <c:out value="${entry.bidderBid}" /></dd></div><div><dt>Final price</dt><dd>₹ <c:out value="${entry.auctionPrice}" /></dd></div><div><dt>Closed</dt><dd><c:out value="${entry.closesAtDisplay}" /></dd></div><div><dt>Status</dt><dd><c:out value="${entry.status}" /> — <c:out value="${entry.outcome}" /></dd></div></dl></article></div></c:forEach></div></c:otherwise></c:choose></section>
</main>
<script nonce="${cspNonce}">(()=>{const trigger=document.getElementById('logout-trigger');if(!trigger)return;const modal=document.getElementById('logout-modal');const cancel=document.getElementById('logout-cancel');const confirm=document.getElementById('logout-confirm');const form=document.getElementById('logout-form');const close=()=>{modal.hidden=true;trigger.focus();};trigger.addEventListener('click',()=>{modal.hidden=false;cancel.focus();});cancel.addEventListener('click',close);confirm.addEventListener('click',()=>form.submit());modal.addEventListener('click',event=>{if(event.target===modal)close();});document.addEventListener('keydown',event=>{if(event.key==='Escape'&&!modal.hidden)close();});})();</script>
</body>
</html>
