<%@ page contentType="text/html;charset=UTF-8" %><%@ taglib prefix="c" uri="jakarta.tags.core" %><%@ taglib prefix="fn" uri="jakarta.tags.functions" %>
<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>My artifacts | Artifact Alley</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"><link href="/css/site.css" rel="stylesheet"></head>
<body><nav class="navbar navbar-dark auction-nav"><div class="container"><a class="navbar-brand" href="/">Artifact Alley</a><a class="btn btn-accent btn-sm" href="/seller/artifacts/new">Submit artifact</a></div></nav><main class="container py-5">
<c:if test="${not empty successMessage}"><div class="alert alert-success"><c:out value="${successMessage}"/></div></c:if><c:if test="${not empty errorMessage}"><div class="alert alert-danger"><c:out value="${errorMessage}"/></div></c:if>
<p class="eyebrow text-dark">SELLER WORKSPACE</p><div class="d-flex flex-wrap justify-content-between align-items-end gap-3 mb-4"><h1 class="mb-0">My artifacts</h1><div><label class="form-label small" for="status-filter">Filter by status</label><select class="form-select" id="status-filter"><option value="ALL">All listings</option><option value="PENDING_APPROVAL">Pending approval</option><option value="REJECTED">Rejected</option><option value="LIVE">Live</option><option value="SOLD">Sold</option><option value="CLOSED">Closed</option><option value="WITHDRAWN">Withdrawn</option></select></div></div>
<c:choose><c:when test="${empty artifacts}"><div class="auth-card p-4"><h2 class="h4">No submissions yet</h2><p class="description">Submit your first artifact to begin administrator review.</p><a class="btn btn-primary" href="/seller/artifacts/new">Submit artifact</a></div></c:when><c:otherwise><div class="row g-4">
<c:forEach items="${artifacts}" var="artifact"><div class="col-md-6 col-lg-4 listing-item" data-status="${artifact.status}"><article class="artifact-card h-100 p-4">
<c:choose><c:when test="${not empty coverImageUrls[artifact.id]}"><img class="artifact-cover mb-3" src="${coverImageUrls[artifact.id]}" alt="${fn:escapeXml(artifact.title)}"></c:when><c:otherwise><div class="artifact-placeholder mb-3">No photo available</div></c:otherwise></c:choose>
<span class="badge text-bg-light align-self-start mb-2"><c:out value="${artifact.status}"/></span><h2 class="h4"><c:out value="${artifact.title}"/></h2><p class="text-muted"><c:out value="${artifact.category}"/> · <c:out value="${artifact.era}"/></p><p class="small mb-1">Starting: ₹ <c:out value="${artifact.startingPrice}"/></p><p class="small mb-1">Current/final: ₹ <c:out value="${artifact.currentPrice}"/></p><p class="small">Bids: <c:out value="${bidCounts[artifact.id]}"/></p>
<c:if test="${artifact.status == 'REJECTED'}"><div class="alert alert-warning"><strong>Changes requested:</strong> <c:out value="${artifact.rejectionReason}"/></div></c:if><p class="small text-muted">Updated <c:out value="${artifact.updatedAt}"/> · closes <c:out value="${artifact.closesAt}"/></p><a class="btn btn-primary mt-auto" href="/seller/artifacts/${artifact.id}">Manage listing</a>
</article></div></c:forEach></div></c:otherwise></c:choose></main><script nonce="${cspNonce}">(()=>{const filter=document.getElementById('status-filter');if(!filter)return;filter.addEventListener('change',()=>document.querySelectorAll('.listing-item').forEach(item=>item.hidden=filter.value!=='ALL'&&item.dataset.status!==filter.value))})();</script></body></html>
